apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- service.yaml
- auth/service-account.yaml
- auth/configmap.yaml
- consumer.yaml

# Note: You need to create the certificate secrets manually
# See auth/certificate-example.md for instructions
# - consumer-client-certs (TLS secret with client certificate)
# - server-ca-bundle (generic secret with CA certificate)
replicas:
- count: 1
  name: cloud-consumer-deployment
images:
- name: cloud-event-consumer
  newName: quay.io/redhat-cne/cloud-event-consumer
  newTag: latest
