apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-auth-config
  namespace: cloud-events
data:
  config.json: |
    {
      "enableMTLS": true,
      "clientCertPath": "/etc/cloud-event-consumer/client-certs/tls.crt",
      "clientKeyPath": "/etc/cloud-event-consumer/client-certs/tls.key",
      "caCertPath": "/etc/cloud-event-consumer/ca-bundle/ca.crt",
      "enableOAuth": true,
      "oauthIssuer": "https://your-oauth-provider.com",
      "oauthJWKSURL": "https://your-oauth-provider.com/.well-known/jwks.json",
      "requiredScopes": ["subscription:create", "events:read"],
      "requiredAudience": "cloud-event-proxy"
    }
